services:
  - type: web
    name: cafeteria-app
    runtime: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cafeteria-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cafeteria-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cafeteria-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cafeteria-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cafeteria-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: errorlog

databases:
  - name: cafeteria-db
    plan: free
    databaseName: cafeteria
    user: cafeteria_user